CREATE TABLE User (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    fullName VARCHAR(30) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    isAdmin INT(1) NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT CHECK(isAdmin=1 OR isAdmin=0),
    CONSTRAINT CHECK(LENGTH(password)>5),
    CONSTRAINT CHECK(LENGTH(fullName)>3) 
);

CREATE TABLE Product (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(20) NOT NULL,
    price BIGINT UNSIGNED NOT NULL,
    quantity INT NOT NULL,
    userID INT(6) UNSIGNED, 
    imgUrl VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (userID) REFERENCES User(id), 
    CONSTRAINT CHECK(price > 0)
);

CREATE TABLE Bill (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    userID INT(6) UNSIGNED,
    productID INT(6) UNSIGNED,
    quantity INT NOT NULL,
    pay INT(1) DEFAULT 0 NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (userID) REFERENCES User(id),
    FOREIGN KEY (productID) REFERENCES Product(id)
);